### ISSUE TITLE
GNU GPL-3.0 

### ISSUE THREAD

**Issue by alerdenisov** [DOkwufulueze/eth-vue#10]
Why not MIT/Apache? I couldn't release whole code of my dApp as open source and as result couldn't use your box at all.

Which part of repository covered with GPL? If I will use only webpack build files could I use MIT?

**Comment by DOkwufulueze** [comment]
Hi, @alerdenisov.

I believe you can release your dApp under any GPL-3.0 compatible licence. And for Webpack build files, since they're webpack sources, I believe you should be able to use MIT.
