### ISSUE TITLE
Compilation failed

### ISSUE THREAD

**Issue by Enggawadhesh** [DOkwufulueze/eth-vue#11]
Hi,
I have installed truffle and then install eth-vue as per your instructions  and got an issue after compilation. I don't have any knowledge about solidity, error on network_id - 3 & 4, I have not checked others network_id
I am a window user and also not installed Ganache & Ropsten.

![error](https://user-images.githubusercontent.com/20462660/37767955-dc4dcd86-2df1-11e8-9c1f-ba2e96444d86.png)

**Comment by DOkwufulueze** [comment]
Hi, @Enggawadhesh.
My guess is that the compilation error you're having seems to be coming from your Solidity compiler version as seen in the screenshot you shared: `...current compiler is 0.4.19+...`.

The pragma statements in the Smart Contracts specify a compiler version 0.4.18, not 0.4.19.

I'll look into this deeply during the weekend, and get back to you.

**Comment by DOkwufulueze** [comment]
Hi, @Enggawadhesh.
I tested thoroughly during the weekend, even wiping out my local version of `eth-vue` and repeating the entire unboxing process. I still couldn't get to replicate your issue. Compilation and migration happened smoothly.

So, the compiler version suspicion I wrote about is still the reason I can see as responsible for your issue.

If there's any helpful information I may need to know surrounding your installation, compilation, and migration that can help in my investigations, please share so I can inspect anew.

**Comment by Enggawadhesh** [comment]
Ok dear, i think it's my compiler issue. it's running now with npm run dev & start
