### ISSUE TITLE
Migrations Issue

### ISSUE THREAD

**Issue by moranthomas** [DOkwufulueze/eth-vue#18]
Hi,

**initially using:** 
Truffle v5.0.3 (core: 5.0.3)
Solidity v0.5.0 (solc-js)
Node v10.11.0

I unboxed the **eth-vue** truffle box and ran a truffle compile but got a bunch of compilation errors so I downgraded the version of solc that truffle uses by modifying the truffle.js config file to match the version of **solidity "0.4.18"** which got rid of all of the compilation errors (as you have previously documented).

However now at the next step, **truffle migrate**.... I get 
Error:  *** Deployment Failed ***
"Setup" -- invalid address (arg="_dbAddress", coderType="address", value=undefined).
    at /Users/thomasmoran/.nvm/versions/node/v10.11.0/lib/node_modules/truffle/build/webpack:/packages/truffle-deployer/src/deployment.js:364:1

Any ideas or suggestions to what might be going wrong?

**Comment by DOkwufulueze** [comment]
Hey, @moranthomas 

I'm looking into this issue, and I'll get back to you once I get useful information.

**Comment by moranthomas** [comment]
Thanks @DOkwufulueze.
I've since I downgraded the version of solc that truffle uses by modifying the truffle.js config file to match the version of solidity in the contracts (solidity 0.4.18;) which got rid of a lot of the issues.
Only then I realised that in your description in the trufflebox website it says it works with truffle4 so I downgraded to that 

- npm uninstall -g truffle
- npm install -g truffle@4.0.0 

Then unboxed, compiled and migrated and that seems to have done the trick.
So I guess the box just needs to be upgraded to work with latest version of truffle ?

**Comment by DOkwufulueze** [comment]
@moranthomas 

Good to know you're good now. Nevertheless, I have begun upgrading `eth-vue`. I've pushed several changes which should resolve all compilation and migration issues related to later versions of Solidity, Truffle, etc.

`eth-vue` now compiles and migrates successfully with `Truffle 5`, `Solidity v0.5.0`, and other related dependencies.
I'll update the README once all upgraded dependencies have been fully tested and found to be OK with `eth-vue`.

**Comment by DOkwufulueze** [comment]
Closing as this issue has been resolved.
