### ISSUE TITLE
getWeb3.js  read properth 'isListening' of undefined

### ISSUE THREAD

**Issue by liuya-dogi** [DOkwufulueze/eth-vue#20]
![image](https://user-images.githubusercontent.com/43056875/61863182-b0f22c80-af01-11e9-8318-c197236af7d1.png)
Got an error on Mac Chrome as shown in the attachment.

**Comment by bearDream** [comment]
Same error...

**Comment by bearDream** [comment]
Shit, I found this problem.
Step1. Add "web3": "^1.2.7" in "dependencies".
Step2. npm install
Ok, Enjoy it.

**Comment by DOkwufulueze** [comment]
Closing as this is now resolved in new updates.
Thanks, @bearDream for the patch.
