### ISSUE TITLE
Error: could not unlock signer account

### ISSUE THREAD

**Issue by osarrouy** [DOkwufulueze/eth-vue#4]
Hi,

Thanks for your boilerplate. That's exactly what i was looking for.

The problem is that when i run the first migration a got a `Error: could not unlock signer account`. 

Any idea ?

**Comment by DOkwufulueze** [comment]
Really sorry about missing this. The problem is coming from the truffle.js file. It contains the following:
```js
module.exports = {
  networks: {
    development: {
      host: "localhost",
      port: 8545,
      network_id: "*", // Match any network id
      from: "0x13ba42b19c25c0f6ecb7ab1c5db8d736231ecb94"
    }
  }
};
```

Open the file, and change the `from` key to your own account: [`from: <your_unlocked_account>`]. Ensure you unlock the account on your node. Then migrate again.

I'll edit the README to contain this directive.

**Comment by osarrouy** [comment]
Thanks a lot !

**Comment by DOkwufulueze** [comment]
Welcome. I appreciate your pointing this out. Thank you.
I hope no other issue will be encountered, but if you do come across any, please let me know again. Let's improve this boilerplate the best we can so others can use it with ease.

**Comment by osarrouy** [comment]
Well. Maybe on thing.

Why did you choose this boilerplate has to run on mainnet and not on a simnet like testrpc ?

When i use test rpc i can't signup or login ...

**Comment by DOkwufulueze** [comment]
No reason actually. I just needed to use a network and MainNet came naturally.

You can undo this too, go to `src/util/constants.js` and you'll see the configuration thus:
```js
export const NETWORKS = {
  '1': 'Main Net',
  '2': 'Deprecated Morden test network',
  '3': 'Ropsten test network',
  '4': 'Rinkeby test network',
  '42': 'Kovan test network',
  '765': 'DanielNet test network',
  'approvedBlockchainNetwork': '1'
}
```

Change `approvedBlockchainNetwork` to the ID of your network of choice.

If your network of choice is not included in the list, you can add it using the pattern you see in the file:
[`<networkId>: <networkName>]`
Then change `approvedBlockchainNetwork` to the id of your network.

Please ignore the `DanielNet test network` with id 765. That's my private blockchain network.
These will make up the update of the README. I'm already on it.

Just curious, was your migration successful?

**Comment by osarrouy** [comment]
Yes. The migration was great. And thanks again for your answer. I go back to you if I have any more questions :)

**Comment by DOkwufulueze** [comment]
The README.md, constants.js, and truffle.js files have been updated based on this issue.
Find updates at https://github.com/DOkwufulueze/eth-vue/tree/v2.1.0

**Comment by DOkwufulueze** [comment]
Closing this issue as it seems inactive.
