### ISSUE TITLE
Insert your unlocked account within the double-quotes of the from key

### ISSUE THREAD

**Issue by covertbert** [DOkwufulueze/eth-vue#6]
What does this mean? Apologies to mark it as an issue as it's obviously nothing broken but I feel a little clarification would be helpful as it seems you're presuming some prerequisite knowledge that many people (myself included) may not have.

**Comment by DOkwufulueze** [comment]
@covertbert, no worries about asking for clarification, it's OK.

To answer your question, Smart Contract migrations [`truffle migrate`] require the ethereum account issuing the `migrate` command to be an unlocked. This means if you're on an ethereum network, say `"development"`, the `account` you wish to make the base account for the `development` network, say `"0xabcdef123456789abce4567328abdc76543acbba"`, must be unlocked for `truffle migrate` to work.

Now, back to `eth-vue`, in the `truffle.js` file, you'll find the following:
```js
module.exports = {
  networks: {
    development: {
      host: "localhost",
      port: 8545,
      network_id: "*", // Match any network id. You may need to replace * with your network Id
      from: "", // Add your unlocked account within the double quotes
      gas: 4444444
    }
  }
};
```
In the exported object above, you see we've left the `from` key blank

        from: "", // Add your unlocked account within the double quotes.

So, **_Insert your unlocked account within the double-quotes of the `from` key_** simply means copy and paste your unlocked account into the double quotes. This would make the account you pasted responsible for issuing the `migrate` command.
In the case of our example account above: `"0xabcdef123456789abce4567328abdc76543acbba"`, you'll now have:

        from: "0xabcdef123456789abce4567328abdc76543acbba", // Add your unlocked account within the double quotes.

Hope this helps.

**Comment by covertbert** [comment]
That's very helpful, thank you very much!

**Comment by DOkwufulueze** [comment]
You're welcome!
