### ISSUE TITLE
How to integrate with ERC20 token

### ISSUE THREAD

**Issue by buhrmi** [DOkwufulueze/eth-vue#7]
Hello,

I'd love to use this to create and transfer ERC20 tokens. Is there a way to combine this with ERC20?

**Comment by DOkwufulueze** [comment]
Hi, @buhrmi,

To create and transfer ERC20 tokens with `eth-vue`, I'll suggest you visit [zeppelin](https://github.com/OpenZeppelin/zeppelin-solidity), and get the necessary directories and Smart Contract files. Add the directories and files to `eth-vue`'s `zeppelin` directory. Once that's done, you can call the required methods as normal.

Visit [zeppelin](https://github.com/OpenZeppelin/zeppelin-solidity) to see the libraries and Smart Contracts you'll need.

**Comment by perfectwebtech** [comment]
hello is there any good api for ERC20 tokens plz help me

**Comment by DOkwufulueze** [comment]
Have you checked [tokenbalance](https://github.com/hunterlong/tokenbalance)?

**Comment by DOkwufulueze** [comment]
Closing as this seems settled.
